### ISSUE TITLE
New codes?

### ISSUE THREAD

**Issue by ghost** [Sunpui/Endless-Crafting#9]
ERROR tera-proxy-game: [dispatch] hook: unrecognized hook target S_FATIGABILITY_POINT<2>
    at new EndlessCrafting (C:\Users\-----\Desktop\proxy\bin\node_modules\Endless-Crafting\index.js:53:11)
    at Dispatch.load (C:\Users\------\Desktop\proxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:210:25)
    at Dispatch.connection.dispatch.on (C:\Users\----\Desktop\proxy\bin\lib\proxy.js:246:29)
    at Dispatch.emit (events.js:182:13)

**Comment by ghost** [comment]
NA protocol
protocol.334245.map
S_FATIGABILITY_POINT = 50429
